# Generated by Django 6.0.6 on 2026-06-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='produc_image', verbose_name='Product Image')),
                ('name', models.CharField(max_length=127, null=True, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Product Price')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount')),
                ('category', models.ManyToManyField(to='store.category')),
            ],
        ),
    ]
