# Generated by Django 6.0.6 on 2026-06-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productcategory_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='battery',
            field=models.CharField(max_length=127, null=True, verbose_name='Product Battery'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=127, null=True, verbose_name='Product Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=127, null=True, verbose_name='Product Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='connectivity',
            field=models.CharField(max_length=127, null=True, verbose_name='Product Connectivity'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, verbose_name='Product Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.CharField(max_length=127, null=True, verbose_name='Product Display'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_model',
            field=models.CharField(max_length=127, null=True, verbose_name='Product Model'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(max_length=127, null=True, verbose_name='Product RAM'),
        ),
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.CharField(max_length=127, null=True, verbose_name='Product Sex'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=127, null=True, verbose_name='Product Size'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(max_length=127, null=True, verbose_name='Product Warranty'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=127, null=True, verbose_name='Product Weight'),
        ),
    ]
