# Generated by Django 6.0.6 on 2026-06-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_battery_product_brand_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='battery',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Product Battery'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Product Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='connectivity',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Product Connectivity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='display',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Product Display'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Product Model'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Product RAM'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sex',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Product Sex'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Product Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Product Warranty'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Product Weight'),
        ),
    ]
