# Generated by Django 6.0.6 on 2026-06-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_color_remove_product_display_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=127, null=True)),
                ('email', models.EmailField(max_length=127, null=True)),
                ('password', models.CharField(max_length=127, null=True)),
            ],
        ),
    ]
